network:
  CNN_Feature_active: None
  CNN_Kernel_size: 5
  IE_feature_channels: 30
  brightness_calculation_option: 1
  device: cuda
  model_illumination_estimator_model: CNN
  number_blocks:
  - 1
  - 2
  - 2
training:
  batch_size: 5
  epochs: 100
  learning_rate: 1e-4
  valid_per_iter: 100
